<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130711151917 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
			// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE chantrea_training_domain_model_topic_trainers_join DROP FOREIGN KEY FK_F3F7BCF6182B982E");
		$this->addSql("CREATE TABLE chantrea_training_domain_model_user (persistence_object_identifier VARCHAR(40) NOT NULL, position VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE chantrea_training_domain_model_user ADD CONSTRAINT FK_AFEE9D8147A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES typo3_party_domain_model_abstractparty (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("DROP TABLE chantrea_training_domain_model_trainer");
		$this->addSql("DROP INDEX IDX_F3F7BCF6182B982E ON chantrea_training_domain_model_topic_trainers_join");
		$this->addSql("ALTER TABLE chantrea_training_domain_model_topic_trainers_join DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE chantrea_training_domain_model_topic_trainers_join CHANGE training_trainer training_user VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE chantrea_training_domain_model_topic_trainers_join ADD CONSTRAINT FK_F3F7BCF68209910A FOREIGN KEY (training_user) REFERENCES chantrea_training_domain_model_user (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_F3F7BCF68209910A ON chantrea_training_domain_model_topic_trainers_join (training_user)");
		$this->addSql("ALTER TABLE chantrea_training_domain_model_topic_trainers_join ADD PRIMARY KEY (training_topic, training_user)");
		$this->addSql("UPDATE typo3_party_domain_model_abstractparty SET dtype='chantrea_training_user' WHERE dtype='chantrea_training_trainer'");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
			// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

		$this->addSql("ALTER TABLE chantrea_training_domain_model_topic_trainers_join DROP FOREIGN KEY FK_F3F7BCF68209910A");
		$this->addSql("CREATE TABLE chantrea_training_domain_model_trainer (persistence_object_identifier VARCHAR(40) NOT NULL, position VARCHAR(255) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ENGINE = InnoDB");
		$this->addSql("ALTER TABLE chantrea_training_domain_model_trainer ADD CONSTRAINT FK_679054B547A46B0A FOREIGN KEY (persistence_object_identifier) REFERENCES typo3_party_domain_model_abstractparty (persistence_object_identifier) ON DELETE CASCADE");
		$this->addSql("DROP TABLE chantrea_training_domain_model_user");
		$this->addSql("DROP INDEX IDX_F3F7BCF68209910A ON chantrea_training_domain_model_topic_trainers_join");
		$this->addSql("ALTER TABLE chantrea_training_domain_model_topic_trainers_join DROP PRIMARY KEY");
		$this->addSql("ALTER TABLE chantrea_training_domain_model_topic_trainers_join CHANGE training_user training_trainer VARCHAR(40) NOT NULL");
		$this->addSql("ALTER TABLE chantrea_training_domain_model_topic_trainers_join ADD CONSTRAINT FK_F3F7BCF6182B982E FOREIGN KEY (training_trainer) REFERENCES chantrea_training_domain_model_trainer (persistence_object_identifier)");
		$this->addSql("CREATE INDEX IDX_F3F7BCF6182B982E ON chantrea_training_domain_model_topic_trainers_join (training_trainer)");
		$this->addSql("ALTER TABLE chantrea_training_domain_model_topic_trainers_join ADD PRIMARY KEY (training_topic, training_trainer)");
	}
}

?>